#
[parameters]
detd = 1
lambda = 1
detsize = 512 512
pixsize = 0.2
stoprad = 10
polarization = x


[make_detector]
out_detector_file = ./det__test.h5 


[emc]
in_photons_file = data/photons.emc
in_detector_file = make_detector:::out_detector_file
num_div = 6
output_folder = data/
log_file = logs/EMC.log
need_scaling = 1
beta_factor = 1.0
beta_schedule = 2.0 10
